sudo: required
language: node_js
node_js:
- 6
install:
- npm install
script:
- npm test && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
  slack:
    secure: lcjjpIGmtjOac4SkeMg6rMcUu+3wee+xgEsBC6a1sYCWGKTxs6x22ezCHwBKbjZ9r14wm+2zOfYuBxWtvxkfduB8WVHH/U+2l5Fto37BxFvWSBqBJy+6BzMz+3gH9JvpHHOjuiqotDX8IQwsQhCgO2MIu+clU3F/T2KT9QtZAFzGnD00vjAkPH+9usxTKfFAmKNwETbTCP3cf3s0KOeX8q3YVW7yYV2Rx3lKT6LDtwzRoO1Fuhp6XNgTkKSWnrbkGsr0terSinkwHj/77cgyrnAVKKUo21Oorz9w6lBTOhvj32H0cShta0zk97+E3bhdhCg9hZtF7oqA+u2thLEWRX2luWlN45X6+kpcrEJYg4Zlhd+ABJyk9a68GwP9H9Kqa8+BxTk4tJzf9w/jgKhFcyM2HMBpD97aGqtQMUKXV5lwQPgutL7eGg8irGKwaidWKT9yWRthAQc0xRiv9/zc6Hwtb9RuRi6KZeyKrLFmDT2PP4Y5NhkDV6XFMaxllx0MSaYC4skl59gbrMl3FZWv8xgJUNHHyxfxheg9Apyf1MXGZOqsIlmqky87pO6csqVL1N5MsKrR12EEzBhW+71VnEPph5vNtTU6gm7sIHCkMPUdCbPNZtBnoK+1SF/T8PehgTPIkakFxmqMNy/ApEFHlUT3/5KvAKs37k481QROGV8=
    on_success: never
    on_failure: always
    on_start: never
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: G50iKhaVQmgEifRbBMV3n07SDhAo8VxGTJYQiaF64hPuw+jlYvdLMr5n8U86HL6XS2yqP55jWJm1JYjpWWASmwBSNTnmMRhny5cP7N0KtsJpQ2rKP7s08Hw24MPZPntuYvX+WmjtMfRnYSTh1O6U7Lb33HvSby9qxg4/bNZo5jN5UEZbZztG+VL+SkaB5J46QJAPJZFFq0TXJaRZ3ygaIA8pAflR8h3c9yCtDkcu3eb3QojTsOigoKD5AUYLzesRgtoJCQvMqQ+SQpKEmWp91sgb+ItdXfXPiur3HxCXuzWtpt1BTSSOyPkISfbKDEwz7wVEzlDx6SRwoXZCFNu7bl/hyLotHYMDGgSVHZ/LHITOdUKb5E4ubJWmKLSnCCxNcVUO3ykw1eXjctikIsNMQnNRXUpWbEGCeDXGUN4jT/2/2CAfwe+ZWCKn53f2kUcAkOLQERiX4KSyHmvfooj1TqtilhnhXyuzFpXf4trQoVnmrVLoszVo7bwJAd9yCRTfHsCC+B1hI/22eWcFPEHF5CJO90gs3cdt4XdBhodESF+ip/QhpyeVmkqc4IDPmKHJ/I5OqSgI+2hCKQpMVAqUAxCo3h/mjPsehqKYEgemJu/Hf+a3R8PRo6kgN4nzJo/tGk05Pr9cbINyjv5s2gKrltEp9g78tuFXMjyZauamna4=
  on:
    repo: kuzzleio/kuzzle-common-objects
    branch: master
