sudo: required
language: node_js
node_js:
- 6
install:
- npm install
script:
- npm test && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
  slack:
    secure: lcjjpIGmtjOac4SkeMg6rMcUu+3wee+xgEsBC6a1sYCWGKTxs6x22ezCHwBKbjZ9r14wm+2zOfYuBxWtvxkfduB8WVHH/U+2l5Fto37BxFvWSBqBJy+6BzMz+3gH9JvpHHOjuiqotDX8IQwsQhCgO2MIu+clU3F/T2KT9QtZAFzGnD00vjAkPH+9usxTKfFAmKNwETbTCP3cf3s0KOeX8q3YVW7yYV2Rx3lKT6LDtwzRoO1Fuhp6XNgTkKSWnrbkGsr0terSinkwHj/77cgyrnAVKKUo21Oorz9w6lBTOhvj32H0cShta0zk97+E3bhdhCg9hZtF7oqA+u2thLEWRX2luWlN45X6+kpcrEJYg4Zlhd+ABJyk9a68GwP9H9Kqa8+BxTk4tJzf9w/jgKhFcyM2HMBpD97aGqtQMUKXV5lwQPgutL7eGg8irGKwaidWKT9yWRthAQc0xRiv9/zc6Hwtb9RuRi6KZeyKrLFmDT2PP4Y5NhkDV6XFMaxllx0MSaYC4skl59gbrMl3FZWv8xgJUNHHyxfxheg9Apyf1MXGZOqsIlmqky87pO6csqVL1N5MsKrR12EEzBhW+71VnEPph5vNtTU6gm7sIHCkMPUdCbPNZtBnoK+1SF/T8PehgTPIkakFxmqMNy/ApEFHlUT3/5KvAKs37k481QROGV8=
    on_success: never
    on_failure: always
    on_start: never
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: FhedETfd/YHyfpqDE99+9FW73MbNc0zh8wHV2VnFEvs3dz4RJaqdpLNCBrXUg4MglBZYEgGadxYV9GHq6dojd46wVCmeLBmC4V83cexX1GUXMblwUF46r/BOjB/dEkRrEArY52h4LAcljbOkYDFICShmZIGXKHq2CKPhhBGIEdngddRYS3s2KxXFVubTduovkm+cp6ltK5r03PRZh4q1r/52BN+JHlAP8qXoael0+ICOr2zFJSTE6CsPwZOvAiDzEjkz9Go8EAHAf4K2VtzbZPz/QT9gHUIKUn5SUSZuxauUQ9PRFhachH1YWg8lvVRzcIG8h7xvFskN/LSuwqvXc7BIiyua6ISJz8ZaWs/JDuE/tWZJv9Jh6Q5XM5Th28DQwBWAscMJqABA0LH0g1c5lQ9sn2iugcMkQFkPtLTdf6yGQvtC6BmsAmJZpAk3tRa5LYef1Hs2ISQjNJW4iA4OXotRRMJ9r0Fn6gsT1xjw5fGBALENnqom6ATGpQDfwit4SqrzpdAh4vygTFWfmzDScfjnRnTPqTfoaLiYiCMNm0J+WLEZ1KZbjWv585yG/HvCbTt18JtIOShpq/ZDAzEJ2z8F26o4OEHeKosa6Z+mtUclBEYpKwwcIotLXXcfmQQWW3GrK0WwuC2fkZiz/VsNAKjLy/aINbZzzoNG52SZXzY=
  on:
    repo: kuzzleio/kuzzle-common-objects
    branch: master
