sudo: required
language: node_js
node_js:
- 4.2.6
install:
- npm install
script:
- npm test && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
  slack:
    secure: lcjjpIGmtjOac4SkeMg6rMcUu+3wee+xgEsBC6a1sYCWGKTxs6x22ezCHwBKbjZ9r14wm+2zOfYuBxWtvxkfduB8WVHH/U+2l5Fto37BxFvWSBqBJy+6BzMz+3gH9JvpHHOjuiqotDX8IQwsQhCgO2MIu+clU3F/T2KT9QtZAFzGnD00vjAkPH+9usxTKfFAmKNwETbTCP3cf3s0KOeX8q3YVW7yYV2Rx3lKT6LDtwzRoO1Fuhp6XNgTkKSWnrbkGsr0terSinkwHj/77cgyrnAVKKUo21Oorz9w6lBTOhvj32H0cShta0zk97+E3bhdhCg9hZtF7oqA+u2thLEWRX2luWlN45X6+kpcrEJYg4Zlhd+ABJyk9a68GwP9H9Kqa8+BxTk4tJzf9w/jgKhFcyM2HMBpD97aGqtQMUKXV5lwQPgutL7eGg8irGKwaidWKT9yWRthAQc0xRiv9/zc6Hwtb9RuRi6KZeyKrLFmDT2PP4Y5NhkDV6XFMaxllx0MSaYC4skl59gbrMl3FZWv8xgJUNHHyxfxheg9Apyf1MXGZOqsIlmqky87pO6csqVL1N5MsKrR12EEzBhW+71VnEPph5vNtTU6gm7sIHCkMPUdCbPNZtBnoK+1SF/T8PehgTPIkakFxmqMNy/ApEFHlUT3/5KvAKs37k481QROGV8=
    on_success: never
    on_failure: always
    on_start: never
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: jnhSsqiXSNj9LS2RzxkBlR+Ks9ekRDSe9E+NS7CssO4XzozEtWAz+t5maKjPm9snl8u/i9rv4NdAeUF7q9RYJvX0FIyTYj022pMIg5Mgq4FMIsBO/remAKRX21HMo360+jDrWmAIalfQp5kj5/l5MDl0vm2VKnkZbMdz0kOYyvn86PSEcYDyQHYvSYGjZCfZX9+KJt2monzl2hlCiLqdtkeJjQ7FIbmqbFaQ1BaHFufB6Z85Sb3v9CzmFGSbC0heZ34vboMFjgZS58ip2X3atCLB13ZK1NWkshvnRXKarHurGOhtDm1iizBGrQOfdvichgBiRUGpXXKeMk51dcxGEydAkjcmDhIj5Y915OeSjT5ZTOK1nbEasXU/0J1W4pIVJgQOfxumIF2Zu/Y6y6k1i6YOGtDPmQSP89S7u1XjcwBfsINJwp6NCc7UdL86saTk7QPP0Sewlhk0XyyAlBizahwumrfZHhIEBCW+hgbUva/5pYHSLOIKdTHSEV/9S5SDYFlC9knZHegiyJjw2Pw3lEw/jTzZurlJ8VRctFoGzmdWaPo3E8OQSafT5AtV8d32+aKRcVy/vDYDhLolLeOHtujQbzW1BLPxTBDroieOyHOSDkkNywoBQ7smzquXeFQvHHcegZcSohHm+uRwLQVAYWCHjV+qVpA5L9rmspPw4hw=
  on:
    repo: kuzzleio/kuzzle-common-objects
    branch: master
