sudo: required
language: node_js
node_js:
- 4.2.6
install:
- npm install
script:
- npm test && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
  slack:
    secure: lcjjpIGmtjOac4SkeMg6rMcUu+3wee+xgEsBC6a1sYCWGKTxs6x22ezCHwBKbjZ9r14wm+2zOfYuBxWtvxkfduB8WVHH/U+2l5Fto37BxFvWSBqBJy+6BzMz+3gH9JvpHHOjuiqotDX8IQwsQhCgO2MIu+clU3F/T2KT9QtZAFzGnD00vjAkPH+9usxTKfFAmKNwETbTCP3cf3s0KOeX8q3YVW7yYV2Rx3lKT6LDtwzRoO1Fuhp6XNgTkKSWnrbkGsr0terSinkwHj/77cgyrnAVKKUo21Oorz9w6lBTOhvj32H0cShta0zk97+E3bhdhCg9hZtF7oqA+u2thLEWRX2luWlN45X6+kpcrEJYg4Zlhd+ABJyk9a68GwP9H9Kqa8+BxTk4tJzf9w/jgKhFcyM2HMBpD97aGqtQMUKXV5lwQPgutL7eGg8irGKwaidWKT9yWRthAQc0xRiv9/zc6Hwtb9RuRi6KZeyKrLFmDT2PP4Y5NhkDV6XFMaxllx0MSaYC4skl59gbrMl3FZWv8xgJUNHHyxfxheg9Apyf1MXGZOqsIlmqky87pO6csqVL1N5MsKrR12EEzBhW+71VnEPph5vNtTU6gm7sIHCkMPUdCbPNZtBnoK+1SF/T8PehgTPIkakFxmqMNy/ApEFHlUT3/5KvAKs37k481QROGV8=
    on_success: never
    on_failure: always
    on_start: never
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: WYCFkd5jodMvQokeubhH1Gt58FUYhexk6REOWPlK3gID4DSzuTDRkzy60wzSNNH3Prw7OLZnW9PhECzP8RQ/mymApWhdNz31F3cr/2MjLbPfzjA55jcW3ssZNP+lfmC0PoomWk8NQBXi4qb76VEFeOBzJSLFMkn26Qr4UC6LNdn4ND4Dv8cORKR0UIjbCnEUHjh+hUs0DFt/LRg+mlSqC6iw1YmT7MDWntKxXzxjaUvAh3ObJfeRJ5YbkSGAJaeef7ZJt9/QG+6mCMgvzVeWSKUZXT2CoCZwqmxpi+JW2h701ujUVIdnlrxkHSnquE6D4wP295VpjeJi0NewFDD+dVNHzP99j/jDI/hJGuiXOGWLY3NqyMbcxAUgJ8aOCUJWnZaPAomNs6xL9mCsGNJkMdmt4NN+9srEdVqohP4c4GbRUZAiZOedVrYPObI95klxzVshJlJ839C9jvsCDs7N+ZFernvr7vtGu11OSE7itOky2GmK6aVsn8BzuVVuLksNl5OcS63QiT11FTlpZYRu0EgOcDozpqSioRdePCr8E1eUm/o9kJZhGT3by2hq98Y5gUZinEf55ahNhLB/FzXClwz4HijdvT+CFrYU6XInsNmoELT5IPL9nho77fAPG1Ne9SMPtANsD5T9jwt0vn88n52rubXye47yPsDxzLUNP6M=
  on:
    repo: kuzzleio/kuzzle-common-objects
    branch: master
