sudo: required
language: node_js
node_js:
- 6
install:
- npm install
script:
- npm test && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
  slack:
    secure: lcjjpIGmtjOac4SkeMg6rMcUu+3wee+xgEsBC6a1sYCWGKTxs6x22ezCHwBKbjZ9r14wm+2zOfYuBxWtvxkfduB8WVHH/U+2l5Fto37BxFvWSBqBJy+6BzMz+3gH9JvpHHOjuiqotDX8IQwsQhCgO2MIu+clU3F/T2KT9QtZAFzGnD00vjAkPH+9usxTKfFAmKNwETbTCP3cf3s0KOeX8q3YVW7yYV2Rx3lKT6LDtwzRoO1Fuhp6XNgTkKSWnrbkGsr0terSinkwHj/77cgyrnAVKKUo21Oorz9w6lBTOhvj32H0cShta0zk97+E3bhdhCg9hZtF7oqA+u2thLEWRX2luWlN45X6+kpcrEJYg4Zlhd+ABJyk9a68GwP9H9Kqa8+BxTk4tJzf9w/jgKhFcyM2HMBpD97aGqtQMUKXV5lwQPgutL7eGg8irGKwaidWKT9yWRthAQc0xRiv9/zc6Hwtb9RuRi6KZeyKrLFmDT2PP4Y5NhkDV6XFMaxllx0MSaYC4skl59gbrMl3FZWv8xgJUNHHyxfxheg9Apyf1MXGZOqsIlmqky87pO6csqVL1N5MsKrR12EEzBhW+71VnEPph5vNtTU6gm7sIHCkMPUdCbPNZtBnoK+1SF/T8PehgTPIkakFxmqMNy/ApEFHlUT3/5KvAKs37k481QROGV8=
    on_success: never
    on_failure: always
    on_start: never
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: Y25l4s5xUeMTRMj8F8MnHhIPjnvA61jNeC/kKhqO8oQhvVz4TVuwsjpzLBQOmstwuhne4ojzVv/7Q/a/H2qy9KFnudq0exZzml7h0/z4mdJSlq+7B1tr0uwkQpYNA254+Fb/A8atPK/G0NmbbUCEk07S7dKsaS5qWclk31HjfPF7c50QiUBRyM1OYQNUanDRnjJjhc8EcUqHKFo4c1livlJP7j0+eLYNyIJ8yEBewH1/svJNsE+NPkOwTQ2xFwkZJt5CeJ8ZEAPwpWtGtYNjsXWY/SjA1PXKdKjHE/QuQ9Jl5NBjV+N0JooYhY1JLrurWN/RdcdgDCIjQuFJsqSmqqi0IVP3p0clN+P7sWymvBD3jN8tfvdRcdi7whN+LCWiA5MRFLfGG5EJ9t4GnU4Jxj0U3q5lVoq5L5hObFLRt6miOPxsTVMXVa5jEqZKKxxdnMhm85ZSGAz+820b/uHMISjNS27SLtFOuaMHOSOnPGoNV8MS5DcCIq1n76SxjHwW/h8i1oWVZILE8joqxZM1yPG512n3arJhoas72LLIa97ZgFZ9SXkWkCBz6mU/7vZHVIhJKCxkSdDmiYhO9AunHrZrYce498WCmpScLh/VwWT112IQHwO+dIpSsGvB2OpXXZfpGNwbXqPZ2msqND260Qy3tlIR1SwOUqABJCENZhc=
  on:
    repo: kuzzleio/kuzzle-common-objects
    branch: master
